name: Build artifact from latest code changes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout vatcansitu
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build artifact from source
      run: msbuild "${env:GITHUB_WORKSPACE}\VATCANSitu.vcxproj"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Plugin DLL
        path: Debug\VATCANSitu.dll
